### ISSUE TITLE
Write basic API wrapper around client-finder interactions.

### ISSUE THREAD

**Issue by creationix** [hookflash/obsolete.opjs#10]
We need a nice library to make requesting and responding to openpeer messages as simple as:

``` js
finder.peerLocationFind(data, callback)
```

Also since sometimes the client needs to respond to requests:

``` js
finder.on("peer-location-find", callback)
```

On the server side we will be a websocket server and be in node.js instead of in a browser, but still need a similar API wrapper.

**Comment by jugglinmike** [comment]
@creationix and I collaborated on this earlier this afternoon. I'll include some of the sample code we drafted in order to document our latest design ideas:

``` javascript
var finder = new Finder({
  peerLocationFind: function (message) {
    return promise;
  }
})
var promise = finder.sessionCreate(message);

var promise = finder.sessionDelete(message);

var promise = finder.sessionKeepAlive(message);

var promise = finder.peerLocationFind(message);

finder.connect(url);
finder.close();
finder.on("connect", callback);
finder.on("connected", callback);
finder.on("close", callback);
finder.on("error", callback);
```

**Comment by creationix** [comment]
I have this one nearly complete.  @jugglinmike, I could use some API review and general cleanup before we wire it live.  Latest code pushed to http://ec2-107-20-118-40.compute-1.amazonaws.com/testfinder.html for testing. (see console)
