### ISSUE TITLE
Setup linux server for deploying the prototype demo

### ISSUE THREAD

**Issue by creationix** [hookflash/obsolete.opjs#12]
This doesn't need much, just a simple linode or EC2 linux with a C toolchain and node.js would be enough.

**Comment by ghost** [comment]
Robin will get you AWS info, once you have received that you can assign this ticket back to your self and setup the server the way you like.

**Comment by ghost** [comment]
Sent credentials to you.

**Comment by creationix** [comment]
Setup EC2 instance with Ubuntu 12.10 and Node 0.10.0

The openpeer/opjs repo is cloned to `/home/ubuntu/opjs` and the server is in the `prototype` directory of that repo.

The upstart script in `/etc/init/node.conf` contains the following:

``` upstart
description "Run node server"

env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

respawn
start on runlevel [23]

script
  cd /home/ubuntu/opjs/prototype
  exec node server.js > access.log 2>> error.log 
end script
```

Also the node server changes are in 25e200fe8518fad4d87be4962737cb92538e4062

**Comment by creationix** [comment]
The server is at http://ec2-107-20-118-40.compute-1.amazonaws.com/

**Comment by creationix** [comment]
For now pushing code updates consist of manually logging into the EC2 instance, running `git pull` on the opjs repo and restarting the node server with `sudo restart node`.  Later we may automate this with a github post commit hook or something.
