### ISSUE TITLE
Integrate or write cross-platform WebRTC wrapper

### ISSUE THREAD

**Issue by creationix** [hookflash/obsolete.opjs#14]
The web client should use WebRTC to display media streams. In order to provide consisent support across both FireFox and Chrome, define an interface that abstracts over these differences. Perhaps we could use https://code.google.com/p/webrtc-samples/source/browse/trunk/apprtc/js/adapter.js

**Comment by yocontra** [comment]
I wrote one https://github.com/wearefractal/holla/blob/master/lib/shims.coffee if it's helpful. Chrome/FF both updated recently and broke interop - their own demos don't work anymore so I have no idea what changed.

**Comment by yocontra** [comment]
Also check out http://www.webrtc.org/interop - some may be dated

**Comment by cadorn** [comment]
https://github.com/HenrikJoreteg/SimpleWebRTC

**Comment by cadorn** [comment]
https://github.com/priologic/easyrtc

**Comment by cadorn** [comment]
https://github.com/webRTC/webRTC.io

**Comment by cadorn** [comment]
https://github.com/kdomagal/Web-RTC

**Comment by yocontra** [comment]
cleaned up my shims quite a bit - https://github.com/wearefractal/holla/blob/0.7/lib/shims.coffee

**Comment by cadorn** [comment]
https://github.com/peers/peerjs

**Comment by cadorn** [comment]
@Contra I like your shim. It seems to be closest to what we need and nothing more. If I was to take it, convert it to plain old JS (not too fond of coffescript), add a cross-browser test suite and publish it to NPM; would you be interested in jointly maintaining it under the `openpeer` umbrella and using it in `holla`?

We need a rock solid shim that is up to date at all times and would be ensuring that it stays up to date to the best of our abilities and available resources. If we collaborate and get some other people on board we may actually manage to do it. I have not found any project that is reliably up to date and used in a real commercial product. We aim to do that this year.

What do you think?

**Comment by yocontra** [comment]
@cadorn - Sounds good to me - let me know when you have the repo up and running. I'll add some more docs to the code that detail why each shim is there and what it does.

**Comment by cadorn** [comment]
@Contra Great! I have created a repo here https://github.com/openpeer/webrtc-shim and added you as a collaborator. We should get to committing the pure JS version and integrating it into our demo in the next couple of weeks.
