### ISSUE TITLE
STUN/TURN prototype servers

### ISSUE THREAD

**Issue by robin-raymond** [hookflash/obsolete.opjs#15]
Need to obtain account/server details.

**Comment by robin-raymond** [comment]
http://www.html5rocks.com/en/tutorials/webrtc/basics/ <-- some details on STUN/TURN

**Comment by Raynos** [comment]
See https://github.com/enobufs/stun and https://github.com/priologic/easyrtc/blob/master/lib/stunserver.js for previous implementations of a node based STUN server.

**Comment by ghost** [comment]
Thx for the tips @Raynos, we had a look at those yesterday.

**Comment by cadorn** [comment]
@robin-raymond Do I need to get one of these up and running?

**Comment by cadorn** [comment]
More implementations here: https://github.com/openpeer/opjs/issues/14
