### ISSUE TITLE
Fix oauth first-time bug

### ISSUE THREAD

**Issue by creationix** [hookflash/obsolete.opjs#22]
The first time a github oauth token is granted the postMessage never makes it to the parent page.

**Comment by ghost** [comment]
Seeing this behavior for all attempted logins = can't get past the login screen. Closed tab, re-opened, CMD+R, login, see the popup, no error, no login.

Not working in Chrome Canary either.

**Comment by creationix** [comment]
Changed the oauth flow to not use a popup window and instead use full-page redirects.

To test any page other than the `/` route you need to specify the `HOME_URL` environment variable.

For example, to test oauth with `/testfinder.html` you need to start the server like:

```
HOME_URL=/testfinder.html node server.js
```

and then point the browser to http://localhost:8080/testfinder.html

**Comment by ghost** [comment]
The demo page still pops a page, but now it loads the login page in the popup. When I click login inside the popup it seems to reload same page = can't log in.

**Comment by creationix** [comment]
I guess I shouldn't have closed this till it was integrated with the real
front-end and pushed to the live server.

**Comment by ghost** [comment]
Ah yea, just figured that was done, my bad. Turning QA knob off for now.
