### ISSUE TITLE
Fix audio stability

### ISSUE THREAD

**Issue by creationix** [hookflash/obsolete.opjs#23]
For some reason, the audio drops out or gets mixed up mid conversation.  This should be fixed.  I'm not sure if the issue lies in our code or the browser's themselves.

**Comment by creationix** [comment]
We made several fixes regarding timing and client state.  The connection is quite stable now, but for some reason audio doesn't always work even though video always does.  FWIW, we've tested other webrtc demos in chrome and they seem to have the same audio issues.  Perhaps this is an issue with chrome itself.

**Comment by cadorn** [comment]
@xxllexx What is the status of this?

**Comment by xxllexx** [comment]
@cadorn i have one idea, but don't know will it works or not, and also i dont know how to reproduce this bug, would be great to have some use case that will help me with reproducing

**Comment by cadorn** [comment]
@elagerway Do you know more about this bug?

**Comment by elagerway** [comment]
@cadorn It could be in our case local audio is looping back to the user, the local user is hearing their own voice in the their speakers. This should not happen. It could be that AEC, (or Echo Control in the case of WebRTC) is not working properly or is simply not turned on. I have these issues consistently on a Macbook, 2.8 Core i7 running 10.8.3 using current Chrome.

**Comment by cadorn** [comment]
@elagerway If this is still an issue, please file issue at: https://github.com/openpeer/opjs-demo/issues
