### ISSUE TITLE
Connect to live `.well-known/openpeer-services-get` test

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.opjs#31]
From nodejs and browser.

Need CORS enabled to connect to it via `POST` from browser: http://enable-cors.org/ `Access-Control-Allow-Origin: *`

**OR**

Serve `.well-known/openpeer-services-get` via `GET`

**Comment by cadorn** [comment]
Could someone craft me a working `curl` request to `https://unstable.hookflash.me/.well-known/openpeer-services-get` or whichever bootstrapper URI works and post it here.

**Comment by adriano-maljkovic** [comment]
There was some issue that caused the Tomcat to stay stuck. It's restarted now, and it's working at the moment. We are trying to find out what caused the problem and to make sure that does not happen again. Anyway, you are using correct url for services-get and here is the working curl request: 

{"request":{"$domain":"unstable.hookflash.me","$id":"0bb169f86f","$handler":"bootstrapper","$method":"services-get"}}

Please let us know, if the server stops working again...

**Comment by cadorn** [comment]
@adriano-maljkovic Ok. I can connect to the bootstrapper now.

But when I make a call to https://unstable.hookflash.me/finders-get I get:

```
{
"result": {
    "$domain": "unstable.hookflash.me",
    "$id": "abc123",
    "$handler": "bootstrapper-finder",
    "$method": "finders-get",
    "$epoch": 1366043998
}
}
```

i.e. no `finders` property.

I will be trying to connect to live finders via websockets later this week.

**Comment by cadorn** [comment]
I need the `Access-Control-Allow-Origin` header set for https://unstable.hookflash.me/signed-salt-get

Also I see the header set to `localhost:8081` for the other requests. Can we set it to `*` for all of them? We will be calling these from multiple different domains.
