### ISSUE TITLE
Finish OPJS boot

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.opjs#75]
$depends https://github.com/openpeer/opjs/issues/74

> Finish OPJS init sequence, specifically identity provider auth (federated first so we can auto-test (vs facebook)); then ensure init sequence still matches live implementation/spec so OPJS can boot (lockbox, grant, certificates etc…).

Recommended steps:
1. [x] Fix idprovider OuterFrame test timeout in hcs-system-tests
2. [ ] Port OuterFrame test harness from hcs-system-tests into opjs test harness (keep both copies in sync as you make changes)
3. [ ] Create Identity-Live test suite
4. [ ] Setup identity-live to go to live identity server
5. [ ] Hookup OuterFrame test harness to test identity-live login to live id provider (make sure non-live tests continue to pass after all changes)
6. [ ] Once identity login into (ONE) identity works move on with rest of boot sequence.

**Comment by creationix** [comment]
OuterFrame test timeout was my submodules being out of date.

**Comment by creationix** [comment]
Hmm, the outerframe test still breaks sometimes and with a several errors.  I guess there are race conditions still.
