### ISSUE TITLE
Contact test has race condition.

### ISSUE THREAD

**Issue by creationix** [hookflash/obsolete.opjs#76]
In the contact test there is a race condition where the contact is still pending after the core is ready:

https://github.com/openpeer/opjs/blob/master/dev/tests-browser/core/10-Contact.js#L34

The following test always fails, but I'm not if that's an unrelated issue or not.

**Comment by cadorn** [comment]
This should fix things. The test is not needed as the logic has changed after I added capability to add identity after boot.

**Comment by creationix** [comment]
Thanks
