### ISSUE TITLE
Project stage

### ISSUE THREAD

**Issue by h2non** [hookflash/obsolete.opjs#78]
What's exactly the current project stage? It seems inactive for more than 6 months.
This initiative is really interesting. There are plans to provide support in the present and future?

**Comment by robin-raymond** [comment]
@h2non Yes, there are plans to continue. We've been wanting to get the ORTC API done inside the W3C ORTC Community Group first. That initiative has been successful. Our focus has been on the mobile C++ version first which are very much nearing market readiness. With that experience we can then apply the knowledge of all the kinks we've had to work out and then do a full opjs version. Hookflash (a smaller company) is sponsoring this open source initiative so we have to prioritize our efforts but we have by no means forgotten about this project! Obviously any help anyone can provide is very much appreciated too.
